- name: Install packages
  ansible.builtin.apt:
    name:
      - postgresql-{{ postgresql_version }}
      - postgresql-contrib
      - libpq-dev
      - acl
      - python3-psycopg2
    state: present

#- name: Check if PostgreSQL is initialized
#  ansible.builtin.stat:
#    path: "{{ postgresql_data_dir }}/pg_hba.conf"
#    register: postgres_data

- name: "Find out if PostgreSQL is initialized"
  ansible.builtin.stat:
    path: "{{ postgresql_data_dir }}/pg_hba.conf"
  register: postgres_data

- name: Empty data dir
  ansible.builtin.file:
    path: "{{ postgresql_data_dir }}"
    state: absent
  when: not postgres_data.stat.exists

- name: Initialize PostgreSQL
  shell: "{{ postgresql_bin_path }}/initdb -D {{ postgresql_data_dir }}"
  become: yes
  become_user: postgres
  when: not postgres_data.stat.exists

- name: Start and enable service
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: true
