- name: set mydistribution
  ansible.builtin.set_fact:
    mydistribution: "{{ 'rhel' if (ansible_distribution == 'Red Hat Enterprise Linux') else (ansible_distribution | lower) }}"
  when:
    ansible_os_family == "RedHat"


- name: Add signing key (CentOS)
  ansible.builtin.rpm_key:
    key: "https://download.docker.com/linux/{{ mydistribution }}/gpg"
    state: present
  when:
    ansible_os_family == "RedHat"

- name: Add repository into repo.d list (CentOS)
  ansible.builtin.yum_repository:
    name: docker
    description: docker repository
    baseurl: "https://download.docker.com/linux/{{ mydistribution }}/$releasever/$basearch/stable"
    enabled: true
    gpgcheck: true
    gpgkey: "https://download.docker.com/linux/{{ mydistribution }}/gpg"
  when:
    ansible_os_family == "RedHat"


- name: Install Docker (CentOS)
  ansible.builtin.yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
    update_cache: true
  when:
    ansible_os_family == "RedHat"


- name: Start Docker (CentOS)
  ansible.builtin.service:
    name: "docker"
    enabled: true
    state: started
  when:
    ansible_os_family == "RedHat"


- name: Add Docker GPG apt Key (Ubuntu)
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when:
    ansible_os_family == "Debian"

- name: Add Docker Repository (Ubuntu)
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present
  when:
    ansible_os_family == "Debian"

- name: Update apt and install docker (Ubuntu)
  ansible.builtin.apt:
    name: docker-ce
    state: latest
    update_cache: true
  when:
    ansible_os_family == "Debian"
